# Generated by Django 4.2.24 on 2025-10-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_rename_servicelinkeditem_serviceitem_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='care_type',
            field=models.CharField(blank=True, db_column='ServCareType', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='level',
            field=models.CharField(blank=True, db_column='ServLevel', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, db_column='ServType', max_length=1, null=True),
        ),
    ]
