# Generated by Django 4.2.26 on 2025-12-23 13:53

import core.fields
import core.utils
import datetime
from django.db import migrations, models
import medical.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_alter_service_care_type_alter_service_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryService',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='LabServiceID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='LabServiceUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('code', models.CharField(db_column='LabServiceCode', max_length=6)),
                ('name', models.CharField(db_column='LabServiceName', max_length=100)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('price', models.DecimalField(db_column='LabServicePrice', decimal_places=2, max_digits=18)),
                ('care_type', models.CharField(db_column='LabServiceCareType', max_length=1)),
                ('frequency', models.SmallIntegerField(blank=True, db_column='LabServiceFrequency', null=True)),
                ('patient_category', models.SmallIntegerField(db_column='LabServicePatCat', default=15)),
                ('maximum_amount', models.DecimalField(blank=True, db_column='MaximumAmount', decimal_places=2, max_digits=18, null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblLabServices',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model, medical.models.ItemOrService),
        ),
    ]
